name: Deploy VS Code Marketplace

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Deploy to Marketplace
        env:
          VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
        if: github.ref == 'refs/tags' && job.status == 'success'
        run: yarn deploy -p $VSCODE_MARKETPLACE_TOKEN
